# SISTEMA-DISTRIBUIDO-MIDDLEWARE-MAIN/middleware/docker-compose.yml
version: '3.8'

services:
  rabbitmq_service: # Nombre del servicio que usarán los demás
    build:
      context: .
      dockerfile: Dockerfile # Usa tu Dockerfile existente en middleware/
    container_name: rabbitmq_broker_shared
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data_shared:/var/lib/rabbitmq
    # Las variables de entorno para usuario/pass ya están en tu Dockerfile del middleware
    # Si tuvieras un rabbitmq.conf que quisieras usar:
    # - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - mi_red_compartida

networks:
  mi_red_compartida:
    external:
      name: mi_red_compartida

volumes:
  rabbitmq_data_shared: