version: '3.8'

services:
  mysql-db:
    image: mysql:8.0  # Cambiar a versión 8.0 que es más estable
    container_name: mysql-bd2
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: bd2
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mi_red_compartida
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pmysql123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  lp2-service:
    build: .
    container_name: lp2-javascript-service
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq_service
      DB_HOST: mysql-db
    networks:
      - mi_red_compartida
    volumes:
      - ./config.json:/app/config.json
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  mi_red_compartida:
    external:
      name: mi_red_compartida